name: Craft CMS deployments

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Pull repository into the current pipeline
      - name: pull repository
        uses: actions/checkout@v2


      # Use a specific version of Node
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16'
          check-latest: true

      # Install PHP dependencies
      #- name: ğŸ˜ Composer install
      #  run: composer install --no-interaction --no-progress --no-suggest --optimize-autoloader

      # Install NPM dependencies
      - name: ğŸŸ¢ NPM install
        run: npm i
        
      # Install Gulp CLI 
      - name: ğŸ¥¤ Gulp install
        run: npm i -g gulp-cli

      # Build assets using locally installed Gulp
      - name: ğŸ¥¤ Build assets with Gulp
        run: npx gulp build

      # ftp
      # exclude web/uploads is there to avoid deleting user uploaded files
      - name: ğŸ“‚ Sync files
        uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1
        with:
          ftp_host: ${{ secrets.FTP_SERVER }}
          ftp_username: ${{ secrets.FTP_USERNAME }}
          ftp_password: ${{ secrets.FTP_PASSWORD }}
          local_source_dir: "./"
          dist_target_dir: ${{ secrets.REMOTE_DIR_PROD}}
          only_newer: true
          #delete: "true"
          exclude: "'^.git/' '^.github/' 'package-lock.json' 'config' '^node_modules/'"
